### ISSUE TITLE
Streaming music gets interrupted & disconnects BT

### ISSUE THREAD

**Issue by taney** [mswlogo/V1Driver-Bugs#28]
Hi, 

I have an iPhone 6S Plus running latest iOS with V1LE. Everything works fine when it's just v1driver or streaming music but not in combination. When I stream music, it's fine until the radar picks up a signal, my music gets interrupted and the Bluetooth drops and reconnects; my music continues to play on the iPhone until the v1 goes back to mute then the music starts connecting back to Bluetooth. I've restarted the iPhone; same thing. Any ideas? Thanks in advance.

**Comment by mswlogo** [comment]
If you always stream music try turning "Use HFP" Off under Sound Settings.

**Comment by mswlogo** [comment]
Closing this due to no response and I believe is user error.
