### ISSUE TITLE
V1Driver Kills Carplay

### ISSUE THREAD

**Issue by FractalFingers** [mswlogo/V1Driver-Bugs#29]
I have a Pioneer 4200NEX with Carplay and use Apple Maps for Nav.
When I start the car, V1Driver automatically comes on and my iPhone no longer works with Carplay.
I'd rather not have to choose between having navigation or control over my Valentine 1
 
Please:
1. add a switch to allow/disable automatic V1Driver startup (easy?) to allow Carplay to work again.
2. investigate mods to allow coexistence with Carplay?
3. investigate mods to allow V1Driver to be an official Carplay app?

Thanks,

**Comment by mswlogo** [comment]
#1 Exists under Settings Bluetooth
#3 Not possible at this time

Need to debug this by RDForum or Email.

**Comment by mswlogo** [comment]
No Response. Closing.
